spring.application.name=vagas

# ------------------------------------
# 1. Configuração do banco de dados PostgreSQL
# ------------------------------------
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
#spring.datasource.username=postgres.yosgjqogwvnjteujaydi
#spring.datasource.password=Q@k$87hJ%pL!2zV#
spring.datasource.driver-class-name=org.postgresql.Driver

# ------------------------------------
# 2. Configuração do JPA/Hibernate
# ------------------------------------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ------------------------------------
# 3. Configuração de Segurança JWT
# ------------------------------------
app.security.jwt.secret=oQ4p9eZ2l5S8T_Kk-xJz7bXgBwM6dF8cI0vR3uY4aW5mZ6o7q8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l7m8n9o0p1q2r3s4t5u6v7w8x9y0z1a2b3c4d5e
#app.security.jwt.secret=SP8QpLTcS584Nlg+mUNqwD+ntqPM8hPKFcpwU5CitnuYp7VzZuJTDN6cqFPzarcNFvxX2LwjU/53412ubGPYNA==

# ------------------------------------
# 4. Configuração OAuth2 (Login Social) - Google
# ------------------------------------
spring.security.oauth2.client.registration.google.client-id=SEU_CLIENT_ID_DO_GOOGLE
spring.security.oauth2.client.registration.google.client-secret=SEU_SECRET_DO_GOOGLE
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.google.scope=profile,email

# A URL do seu frontend/SPA que irá receber o token JWT
app.oauth2.redirectUri=http://localhost:3000/oauth2/redirect

# ------------------------------------
# 5. Configuração de E-mail (SMTP)
# ------------------------------------
spring.mail.host=smtp.gmail.com 
spring.mail.port=587 
spring.mail.username=conectajob2025@gmail.com
spring.mail.password=gxqw gpye pcow cvja
#spring.mail.password=Con&ct@J0b2025
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true